"""
SNAPHU phase unwrapping for processed Capella InSAR pairs.

Reads ifg_goldstein.tif (2-band Re/Im) and coherence.tif from each pair
directory, writes SNAPHU binary inputs, runs SNAPHU via subprocess, and
saves the unwrapped phase as unw_phase.tif (single-band float32 GeoTIFF).

SNAPHU availability
-------------------
Check with: which snaphu
Install:    conda install -c conda-forge snaphu

Usage
-----
# Unwrap all processed pairs:
python scripts/unwrap_snaphu.py --pairs_dir data/processed/pairs

# Limit to 50 pairs with 2 workers:
python scripts/unwrap_snaphu.py \
    --pairs_dir data/processed/pairs \
    --max_pairs 50 \
    --mode DEFO \
    --workers 2
"""

from __future__ import annotations

import argparse
import concurrent.futures
import logging
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

import numpy as np

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

SNAPHU_CMD = "snaphu"


# ---------------------------------------------------------------------------
# SNAPHU helpers
# ---------------------------------------------------------------------------

def check_snaphu(snaphu_bin: str = SNAPHU_CMD) -> bool:
    """Return True if SNAPHU is on PATH / callable."""
    return shutil.which(snaphu_bin) is not None


def write_snaphu_inputs(
    wrapped_phase: np.ndarray,
    coherence: np.ndarray,
    work_dir: Path,
) -> Path:
    """
    Write phase and coherence as raw float32 binary files.

    Parameters
    ----------
    wrapped_phase : np.ndarray
        (H, W) float32 wrapped phase in radians.
    coherence : np.ndarray
        (H, W) float32 coherence in [0, 1].
    work_dir : Path
        Working directory to write files into.

    Returns
    -------
    work_dir
    """
    wrapped_phase.astype("float32").tofile(work_dir / "phase.float")
    coherence.astype("float32").tofile(work_dir / "coherence.float")
    return work_dir


def write_snaphu_config(
    work_dir: Path,
    nrows: int,
    ncols: int,
    mode: str = "DEFO",
    tiles: int = 1,
) -> Path:
    """
    Write a SNAPHU configuration file.

    Parameters
    ----------
    work_dir : Path
        Directory where config and binary files live.
    nrows, ncols : int
        Image dimensions.
    mode : str
        SNAPHU mode — 'DEFO' (deformation) or 'TOPO' (topographic).
    tiles : int
        Number of tile rows/cols for tiled processing (use > 1 for large images).

    Returns
    -------
    Path to the written config file.
    """
    if mode not in ("DEFO", "TOPO"):
        raise ValueError(f"mode must be 'DEFO' or 'TOPO', got '{mode}'")

    tile_lines = ""
    if tiles > 1:
        tile_lines = f"\nNTILEROW        {tiles}\nNTILECOL        {tiles}\n"

    conf = f"""# Auto-generated by scripts/unwrap_snaphu.py
INFILE           phase.float
CORRFILE         coherence.float
OUTFILE          unwrapped.float
LINELENGTH       {ncols}
NLINES           {nrows}
NCORRLOOKS       9
INITMETHOD       MST
{tile_lines}"""

    conf_path = work_dir / "snaphu.conf"
    conf_path.write_text(conf)
    return conf_path


def run_snaphu(work_dir: Path, snaphu_bin: str = SNAPHU_CMD) -> bool:
    """
    Execute SNAPHU in `work_dir` using snaphu.conf.

    Returns True on success, False on non-zero return code.
    """
    result = subprocess.run(
        [snaphu_bin, "-f", "snaphu.conf"],
        cwd=work_dir,
        capture_output=True,
        text=True,
        timeout=3600,  # 1-hour hard limit per pair
    )
    if result.returncode != 0:
        log.error("SNAPHU failed (rc=%d):\n%s", result.returncode, result.stderr[-2000:])
        return False
    return True


def read_snaphu_output(work_dir: Path, shape: tuple[int, int]) -> np.ndarray:
    """
    Read SNAPHU unwrapped output binary into a (H, W) float32 array.

    Pixels that SNAPHU could not unwrap are set to NaN by convention
    (SNAPHU writes them as 0.0, but we treat the coherence-masked region
    as NaN after reading).
    """
    out_path = work_dir / "unwrapped.float"
    raw = np.fromfile(out_path, dtype="float32")
    if raw.size != shape[0] * shape[1]:
        raise ValueError(
            f"SNAPHU output size mismatch: expected {shape[0]*shape[1]}, got {raw.size}"
        )
    return raw.reshape(shape)


# ---------------------------------------------------------------------------
# End-to-end per-pair processing
# ---------------------------------------------------------------------------

def process_pair(
    pair_dir: Path,
    out_dir: Optional[Path] = None,
    mode: str = "DEFO",
    coh_mask_threshold: float = 0.1,
    snaphu_bin: str = SNAPHU_CMD,
) -> Optional[Path]:
    """
    Unwrap one pair directory end-to-end.

    Steps
    -----
    1. Load ifg_goldstein.tif (2-band Re/Im) → wrapped phase via arctan2
    2. Load coherence.tif
    3. Mask low-coherence pixels before SNAPHU (set phase=0, coh=0)
    4. Write SNAPHU inputs and config in a temp directory
    5. Run SNAPHU
    6. Read output; set NaN where coherence < coh_mask_threshold
    7. Save unw_phase.tif with the same georeferencing as ifg_goldstein.tif

    Parameters
    ----------
    pair_dir : Path
        Processed pair directory containing ifg_goldstein.tif, coherence.tif.
    out_dir : Path, optional
        Where to save unw_phase.tif. Defaults to pair_dir.
    mode : str
        SNAPHU mode ('DEFO' or 'TOPO').
    coh_mask_threshold : float
        Pixels below this coherence are set to 0 before passing to SNAPHU
        and to NaN in the output (they cannot be reliably unwrapped).
    snaphu_bin : str
        Path / name of the SNAPHU executable.

    Returns
    -------
    Path to unw_phase.tif on success, None on failure.
    """
    try:
        import rasterio
        from rasterio.transform import from_bounds
    except ImportError:
        log.error("rasterio not available.")
        return None

    ifg_path = pair_dir / "ifg_goldstein.tif"
    coh_path = pair_dir / "coherence.tif"

    if not ifg_path.exists() or not coh_path.exists():
        log.warning("Missing files in %s — skipping.", pair_dir.name)
        return None

    # --- Load interferogram ---
    try:
        with rasterio.open(ifg_path) as src:
            re_band = src.read(1).astype(np.float32)
            im_band = src.read(2).astype(np.float32)
            profile = src.profile.copy()
        with rasterio.open(coh_path) as src:
            coherence = src.read(1).astype(np.float32)
    except Exception as e:
        log.warning("Read error in %s: %s", pair_dir.name, e)
        return None

    wrapped_phase = np.arctan2(im_band, re_band)
    H, W = wrapped_phase.shape

    # --- Coherence mask: zero out unreliable pixels for SNAPHU ---
    low_coh_mask = coherence < coh_mask_threshold
    wrapped_phase_masked = wrapped_phase.copy()
    coherence_masked = coherence.copy()
    wrapped_phase_masked[low_coh_mask] = 0.0
    coherence_masked[low_coh_mask] = 0.0

    # Adjust tile count for large images
    tiles = 1
    if max(H, W) > 8192:
        tiles = 4
    elif max(H, W) > 4096:
        tiles = 2

    # --- SNAPHU in temp directory ---
    with tempfile.TemporaryDirectory(prefix="snaphu_") as tmp:
        tmp_path = Path(tmp)
        write_snaphu_inputs(wrapped_phase_masked, coherence_masked, tmp_path)
        write_snaphu_config(tmp_path, nrows=H, ncols=W, mode=mode, tiles=tiles)

        ok = run_snaphu(tmp_path, snaphu_bin=snaphu_bin)
        if not ok:
            return None

        try:
            unw = read_snaphu_output(tmp_path, shape=(H, W))
        except Exception as e:
            log.error("Failed to read SNAPHU output for %s: %s", pair_dir.name, e)
            return None

    # --- Post-process: mask low-coherence pixels as NaN ---
    unw[low_coh_mask] = float("nan")

    # --- Save unw_phase.tif ---
    dest_dir = out_dir if out_dir is not None else pair_dir
    dest_dir.mkdir(parents=True, exist_ok=True)
    out_path = dest_dir / "unw_phase.tif"

    out_profile = {
        "driver":     "GTiff",
        "dtype":      "float32",
        "count":      1,
        "height":     H,
        "width":      W,
        "compress":   "deflate",
        "tiled":      True,
        "blockxsize": 256,
        "blockysize": 256,
    }
    # Preserve georeferencing from the interferogram
    if profile.get("crs"):
        out_profile["crs"] = profile["crs"]
    if profile.get("transform"):
        out_profile["transform"] = profile["transform"]

    try:
        with rasterio.open(out_path, "w", **out_profile) as dst:
            dst.write(unw, 1)
    except Exception as e:
        log.error("Failed to save %s: %s", out_path, e)
        return None

    log.info("Saved %s (nan_frac=%.2f%%)",
             out_path, 100 * float(np.isnan(unw).mean()))
    return out_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Batch SNAPHU phase unwrapping for processed Capella pairs.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--pairs_dir", required=True,
                   help="Root directory containing per-pair subdirectories.")
    p.add_argument("--out_dir", default=None,
                   help="Output directory (default: same as each pair_dir).")
    p.add_argument("--max_pairs", type=int, default=None,
                   help="Maximum number of pairs to process.")
    p.add_argument("--mode", choices=["DEFO", "TOPO"], default="DEFO",
                   help="SNAPHU unwrapping mode.")
    p.add_argument("--coh_threshold", type=float, default=0.1,
                   help="Coherence below which pixels are masked (set to NaN in output).")
    p.add_argument("--workers", type=int, default=2,
                   help="Number of parallel worker threads.")
    p.add_argument("--snaphu_bin", default=SNAPHU_CMD,
                   help="SNAPHU executable path or name.")
    return p.parse_args()


def main() -> None:
    args = parse_args()

    # Check SNAPHU availability first
    if not check_snaphu(args.snaphu_bin):
        log.error(
            "SNAPHU not found at '%s'.\n"
            "Install with: conda install -c conda-forge snaphu\n"
            "Or specify path with --snaphu_bin /path/to/snaphu",
            args.snaphu_bin,
        )
        raise SystemExit(1)

    pairs_dir = Path(args.pairs_dir)
    if not pairs_dir.is_dir():
        log.error("pairs_dir does not exist: %s", pairs_dir)
        raise SystemExit(1)

    pair_dirs = sorted(p for p in pairs_dir.iterdir() if p.is_dir())
    # Skip already unwrapped pairs
    pair_dirs = [d for d in pair_dirs if not (d / "unw_phase.tif").exists()]
    log.info("Found %d pair directories to unwrap", len(pair_dirs))

    if args.max_pairs:
        pair_dirs = pair_dirs[: args.max_pairs]
        log.info("Capped at %d pairs", len(pair_dirs))

    out_dir = Path(args.out_dir) if args.out_dir else None

    ok_count = fail_count = 0

    def _unwrap(pd_dir: Path) -> bool:
        result = process_pair(
            pd_dir,
            out_dir=out_dir,
            mode=args.mode,
            coh_mask_threshold=args.coh_threshold,
            snaphu_bin=args.snaphu_bin,
        )
        return result is not None

    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as ex:
        futures = {ex.submit(_unwrap, d): d.name for d in pair_dirs}
        for fut in concurrent.futures.as_completed(futures):
            name = futures[fut]
            try:
                success = fut.result()
            except Exception as e:
                log.error("Unexpected error for %s: %s", name, e)
                success = False
            if success:
                ok_count += 1
                log.info("OK  %s", name)
            else:
                fail_count += 1
                log.warning("FAIL %s", name)

    log.info("Done. %d succeeded, %d failed.", ok_count, fail_count)


if __name__ == "__main__":
    main()
